<?php
namespace App\Controller;
use App\Core\{Auth,Controller};use App\Repository\{CourseRepository,FacultyRepository,LecturerRepository,SemesterRepository};
class CourseController extends Controller {
 public function __construct(private \PDO $pdo){}
 private function repo():CourseRepository{return new CourseRepository($this->pdo);}
 private function validate(array $d):array{$e=[];if($d['code']==='')$e['code']='Mã học phần là bắt buộc.';elseif(!preg_match('/^[A-Za-z0-9._-]{2,50}$/',$d['code']))$e['code']='Mã 2-50 ký tự, chỉ gồm chữ, số, ., _, -.';elseif($this->repo()->codeExists($d['code'],$d['id']))$e['code']='Mã học phần đã tồn tại.';if($d['name']==='')$e['name']='Tên học phần là bắt buộc.';elseif(mb_strlen($d['name'])>150)$e['name']='Tên học phần tối đa 150 ký tự.';if(!filter_var($d['credits']??null,FILTER_VALIDATE_INT)||$d['credits']<1||$d['credits']>10)$e['credits']='Số tín chỉ phải từ 1 đến 10.';if(mb_strlen($d['description'])>2000)$e['description']='Mô tả tối đa 2000 ký tự.';if(!$d['faculty_ids'])$e['faculty_ids']='Phải chọn ít nhất một khoa.';if(!$d['semester_ids'])$e['semester_ids']='Phải chọn ít nhất một học kỳ.';if(!$d['lecturer_ids'])$e['lecturer_ids']='Phải chọn ít nhất một giảng viên có thể dạy.';return$e;}
 public function index():void{Auth::requireRole('admin');$q=trim($_GET['q']??'');$page=max(1,(int)($_GET['page']??1));$r=$this->repo();$total=$r->count($q);[$page,$per,$off,$pages]=paginate($page,8,$total);$this->view('admin/courses/index',['rows'=>$r->findPage($q,$per,$off),'q'=>$q,'page'=>$page,'pages'=>$pages]);}
 public function create():void{$this->form(true);}public function edit():void{$this->form(false);}private function form(bool $create):void{Auth::requireRole('admin');$id=(int)($_GET['id']??0);$ex=$create?null:$this->repo()->findById($id);if(!$create&&!$ex){http_response_code(404);exit('Không tìm thấy học phần.');}$d=$ex?array_merge($ex,['status'=>(int)$ex['status']]):['id'=>0,'code'=>'','name'=>'','credits'=>'','description'=>'','status'=>1,'faculty_ids'=>[],'semester_ids'=>[],'lecturer_ids'=>[]];$errs=[];if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$d=['id'=>$id,'code'=>strtoupper(post_string('code')),'name'=>post_string('name'),'credits'=>post_int('credits'),'description'=>post_string('description'),'status'=>isset($_POST['status'])?1:0,'faculty_ids'=>selectedIds('faculty_ids'),'semester_ids'=>selectedIds('semester_ids'),'lecturer_ids'=>selectedIds('lecturer_ids')];$errs=$this->validate($d);if(!$errs){try{if($create)$this->repo()->create($d);else$this->repo()->update($id,$d);flash('success',$create?'Đã tạo học phần và danh sách khoa/GV có thể dạy.':'Đã cập nhật học phần.');clearFormMemory();redirect('admin/courses');}catch(\Throwable$e){$errs['general']='Không thể lưu học phần. Kiểm tra dữ liệu liên kết.';}}rememberForm($d,$errs);}else clearFormMemory();$this->view('admin/courses/form',['create'=>$create,'data'=>$d,'errors'=>$errs,'faculties'=>(new FacultyRepository($this->pdo))->findAll(),'semesters'=>(new SemesterRepository($this->pdo))->findAll(),'lecturers'=>(new LecturerRepository($this->pdo))->allActive()]);}
 public function delete():void{Auth::requireRole('admin');verify_csrf();$id=post_int('id');try{$this->repo()->delete($id);flash('success','Đã xóa học phần.');}catch(\Throwable$e){flash('error','Không thể xóa học phần vì đã có lớp/đăng ký liên quan.');}redirect('admin/courses');}
}
