<?php
namespace App\Controller;
use App\Core\{Auth,Controller};use App\Repository\SemesterRepository;
class SemesterController extends Controller {public function __construct(private \PDO $pdo){}private function repo():SemesterRepository{return new SemesterRepository($this->pdo);}private function validate(array $d):array{$e=[];if($d['name']==='')$e['name']='Tên học kỳ bắt buộc.';elseif(mb_strlen($d['name'])>100)$e['name']='Tên học kỳ tối đa 100 ký tự.';if(!preg_match('/^\d{4}-\d{4}$/',$d['academic_year']))$e['academic_year']='Năm học dạng YYYY-YYYY.';if(!in_array($d['term'],['1','2','3'],true))$e['term']='Học kỳ không hợp lệ.';foreach(['study_start','study_end','registration_start','registration_end'] as $k)if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$d[$k]))$e[$k]='Ngày không hợp lệ.';if(!$e&&$d['study_start']>$d['study_end'])$e['study_end']='Ngày kết thúc học phải sau ngày bắt đầu.';if(!$e&&$d['registration_start']>$d['registration_end'])$e['registration_end']='Thời gian đăng ký không hợp lệ.';if(!$e&&($d['registration_start']<$d['study_start']||$d['registration_end']>$d['study_end']))$e['registration_start']='Đợt đăng ký phải nằm trong thời gian học kỳ.';return$e;}
 public function index():void{Auth::requireRole('admin');$this->view('admin/semesters/index',['rows'=>$this->repo()->findAll()]);}
 public function create():void{$this->form(true);}public function edit():void{$this->form(false);}private function form(bool $create):void{Auth::requireRole('admin');$id=(int)($_GET['id']??0);$ex=$create?null:$this->repo()->findById($id);$d=$ex?:['name'=>'','academic_year'=>'2026-2027','term'=>'1','study_start'=>'','study_end'=>'','registration_start'=>'','registration_end'=>'','status'=>1];$errs=[];if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$d=['name'=>post_string('name'),'academic_year'=>post_string('academic_year'),'term'=>post_string('term'),'study_start'=>post_string('study_start'),'study_end'=>post_string('study_end'),'registration_start'=>post_string('registration_start'),'registration_end'=>post_string('registration_end'),'status'=>isset($_POST['status'])?1:0];$errs=$this->validate($d);if(!$errs){try{if($create)$this->repo()->create($d);else$this->repo()->update($id,$d);flash('success',$create?'Đã tạo học kỳ.':'Đã cập nhật học kỳ.');clearFormMemory();redirect('admin/semesters');}catch(\Throwable$e){$errs['general']='Không thể lưu học kỳ.';}}rememberForm($d,$errs);}else clearFormMemory();$this->view('admin/semesters/form',['create'=>$create,'data'=>$d,'errors'=>$errs]);}
 public function toggle():void{Auth::requireRole('admin');verify_csrf();$id=post_int('id');try{$this->repo()->toggleRegistration($id);flash('success','Đã thay đổi trạng thái đợt đăng ký.');}catch(\Throwable$e){flash('error','Không thể thay đổi trạng thái.');}redirect('admin/semesters');}
 public function delete():void{Auth::requireRole('admin');verify_csrf();try{$this->repo()->delete(post_int('id'));flash('success','Đã xóa học kỳ.');}catch(\Throwable$e){flash('error','Không thể xóa học kỳ vì còn dữ liệu lớp.');}redirect('admin/semesters');}
}
