<?php
namespace App\Controller;
use App\Core\{Auth,Controller};use App\Repository\{StudentRepository,FacultyRepository};
class StudentController extends Controller {public function __construct(private \PDO $pdo){} private function repo():StudentRepository{return new StudentRepository($this->pdo);} private function validate(array $d,bool $create):array{$e=[];$fields=['student_code'=>'Mã sinh viên','full_name'=>'Họ tên','faculty_id'=>'Khoa','class_name'=>'Lớp','cohort'=>'Khóa'];foreach($fields as $k=>$label)if(($d[$k]??'')==='')$e[$k]="$label là bắt buộc.";if($d['student_code']!==''&&!preg_match('/^[A-Za-z0-9._-]{2,30}$/',$d['student_code']))$e['student_code']='Mã sinh viên 2-30 ký tự, chỉ gồm chữ, số, ., _, -.';foreach(['full_name'=>100,'class_name'=>80,'cohort'=>20] as $k=>$max)if(mb_strlen($d[$k]??'')>$max)$e[$k]="Không được vượt quá $max ký tự.";if(!filter_var($d['faculty_id']??null,FILTER_VALIDATE_INT))$e['faculty_id']='Vui lòng chọn khoa hợp lệ.';if($create){if(($d['username']??'')===''||strlen($d['username'])>50)$e['username']='Tên đăng nhập bắt buộc, tối đa 50 ký tự.';if(strlen($d['password']??'')<6)$e['password']='Mật khẩu tối thiểu 6 ký tự.';}return$e;}
 public function index():void{Auth::requireRole('admin');$q=trim($_GET['q']??'');$page=max(1,(int)($_GET['page']??1));$r=$this->repo();$total=$r->count($q);[$page,$per,$off,$pages]=paginate($page,8,$total);$this->view('admin/students/index',['rows'=>$r->findPage($q,$per,$off),'q'=>$q,'page'=>$page,'pages'=>$pages]);}
 public function create():void{$this->form(true);}
 public function edit():void{$this->form(false);}
 private function form(bool $create):void{Auth::requireRole('admin');$r=$this->repo();$id=(int)($_GET['id']??0);$existing=$create?null:$r->findById($id);if(!$create&&!$existing){http_response_code(404);exit('Không tìm thấy sinh viên.');}$data=$existing?array_merge($existing,['password'=>'']):['student_code'=>'','full_name'=>'','faculty_id'=>'','class_name'=>'','cohort'=>'','username'=>'','password'=>'','status'=>1];$errs=[];if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$data=['student_code'=>strtoupper(post_string('student_code')),'full_name'=>post_string('full_name'),'faculty_id'=>post_int('faculty_id'),'class_name'=>post_string('class_name'),'cohort'=>post_string('cohort'),'username'=>strtolower(post_string('username')),'password'=>(string)($_POST['password']??''),'status'=>isset($_POST['status'])?1:0];$errs=$this->validate($data,$create);if(!$errs){try{if($create)$r->create($data);else{$r->update($id,$data);}flash('success',$create?'Đã thêm sinh viên.':'Đã cập nhật sinh viên.');clearFormMemory();redirect('admin/students');}catch(\Throwable$e){$errs['general']=str_contains($e->getMessage(),'Duplicate')?'Mã sinh viên hoặc tên đăng nhập đã tồn tại.':'Không thể lưu sinh viên.';}}rememberForm($data,$errs);}else clearFormMemory();$this->view('admin/students/form',['create'=>$create,'data'=>$data,'errors'=>$errs,'faculties'=>(new FacultyRepository($this->pdo))->findAll()]);}
 public function delete():void{Auth::requireRole('admin');verify_csrf();$id=post_int('id');if(!$id){flash('error','ID không hợp lệ.');redirect('admin/students');}try{$this->repo()->delete($id);flash('success','Đã xóa sinh viên.');}catch(\Throwable$e){flash('error','Không thể xóa sinh viên vì còn dữ liệu liên quan.');}redirect('admin/students');}
}
